#!/bin/bash

export PS1='[\u@\h \W]\$ '

export I_MPI_LIBRARY_KIND=release_mt
source /home/proj/atnw/honda/intel/oneapi/setvars.sh
source /home/proj/atnw/honda/intel/oneapi/mkl/latest/env/vars.sh

OMPI_HOME=/home/proj/atnw/local
#OMPI_HOME=/home/proj/atnw/honda/lib/ompi/4.0.7/gcc
export PATH=${OMPI_HOME}/bin:${PATH}
export LD_LIBRARY_PATH=${OMPI_HOME}/lib:${LD_LIBRARY_PATH}

export LD_LIBRARY_PATH=/home/proj/atnw/honda/lib/local:/lib64:${LD_LIBRARY_PATH}
